version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=host.docker.internal
      - DB_NAME=andres_db
      - DB_USER=postgres
      - DB_PASSWORD=admin

  frontend: 
    build: 
      context: .
      dockerfile: Dockerfiles/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=300
      - HOST=0.0.0.0