version: '3.8'
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  
  frontend: 
    build: 
      context: .
      dockerfile: Dockerfiles/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=300
      - HOST=0.0.0.0


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: